import { motion, useScroll, useTransform } from "framer-motion";
import { useRef } from "react";
import Scene3D from "./Scene3D";

export default function App() {
  const containerRef = useRef(null);
  const { scrollYProgress } = useScroll({ target: containerRef });
  
  // High-range parallax for strong 3D depth perception
  const sceneY = useTransform(scrollYProgress, [0, 1], ["0%", "80%"]);
  const sceneScale = useTransform(scrollYProgress, [0, 1], [1, 0.7]);

  return (
    <div ref={containerRef} className="bg-black text-white font-sans relative min-h-screen selection:bg-cyan-500/30">
      
      {/* 3D Scene Background */}
      <motion.div 
        className="fixed inset-0 pointer-events-auto" 
        style={{ y: sceneY, scale: sceneScale, zIndex: 0 }}
      >
        <Scene3D />
      </motion.div>

      {/* Main Content Overlay */}
      <div className="relative z-10 w-full flex flex-col items-center">
        
        {/* --- 1. HERO SECTION --- */}
        <section className="min-h-screen w-full flex flex-col justify-center items-center text-center px-6 pointer-events-none">
          <motion.div
            initial={{ opacity: 0, scale: 0.9, y: 30 }}
            animate={{ opacity: 1, scale: 1, y: 0 }}
            transition={{ duration: 1.5, ease: "easeOut" }}
            className="pointer-events-auto backdrop-blur-md bg-black/30 p-12 rounded-[3rem] border border-white/5 shadow-2xl max-w-5xl"
          >
            <div className="text-cyan-400 font-mono text-xs md:text-sm tracking-widest mb-6 uppercase flex mx-auto max-w-2xl justify-center gap-4 flex-wrap">
              <span>ARAV, MADHAN & SHUBHDEEP</span>
              <span className="hidden md:inline">•</span>
              <span>VIT-AP UNIVERSITY</span>
              <span className="hidden md:inline">•</span>
              <span>THESIS 2026</span>
            </div>
            <h1 className="text-5xl md:text-8xl font-bold leading-tight tracking-tight mb-4">
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-purple-400 via-cyan-400 to-blue-400">
                LLM-Augmented
              </span>
              <br />
              RL
            </h1>

            <p className="mt-8 text-xl md:text-2xl text-gray-300 max-w-3xl mx-auto font-light leading-relaxed">
              Can AI that <span className="text-white font-medium">reads the news</span> outperform AI that <span className="text-white font-medium">knows the physical truth</span>?
            </p>
          </motion.div>

          <motion.div 
            animate={{ y: [0, 10, 0] }} 
            transition={{ repeat: Infinity, duration: 2 }}
            className="absolute bottom-10 text-gray-500 font-mono text-sm tracking-widest uppercase"
          >
            Scroll to Explore Thesis ↓
          </motion.div>
        </section>

        {/* --- 2. WHAT IS THE PROJECT? --- */}
        <SectionContainer>
          <SectionHeader title="1. What is the Project?" subtitle="THE CORE PROBLEM & PROPOSED SOLUTION" />
          <div className="grid md:grid-cols-2 gap-12 text-gray-300 font-light text-lg">
            <RevealBox delay={0.1}>
              <h3 className="text-2xl font-bold text-white mb-4 font-sans">The Core Problem</h3>
              <p className="mb-4">
                Traditional supply chain management relies on fixed mathematical formulas (like the <em>"order Q units when inventory drops below s"</em> policy) to decide when and how much inventory to order.
              </p>
              <p>
                While these work fine under normal conditions, they completely collapse during major disruptions (e.g., natural disasters, port strikes, geopolitical conflicts). They react, but they cannot anticipate.
              </p>
            </RevealBox>
            
            <RevealBox delay={0.3} highlight>
              <h3 className="text-2xl font-bold text-cyan-400 mb-4 font-sans">The Proposed Solution</h3>
              <p className="mb-4 text-gray-200">
                This project explores whether we can train AI agents using <strong>Reinforcement Learning (RL)</strong> to manage inventory instead of fixed formulas. 
              </p>
              <p className="text-gray-200">
                More importantly, it tests an <strong>LLM-Augmented approach</strong>, where the RL agent actively receives a "risk score" generated by an AI reading real-time news headlines. The goal: Does reading the news allow an agent to survive supply chain shocks better than an agent acting blindly or using strict binary logic?
              </p>
            </RevealBox>
          </div>
        </SectionContainer>

        {/* --- 3. THE RESEARCH BENCHMARK --- */}
        <SectionContainer reverse>
          <SectionHeader title="2. The Research Benchmark" subtitle="STRANIERI & STELLA (2023)" textAlign="right" />
          <div className="grid md:grid-cols-12 gap-8 text-gray-300 font-light text-lg">
            <div className="md:col-span-5 flex items-center justify-center">
              <RevealBox glowColor="rgba(168,85,247,0.2)">
                <div className="text-center p-6">
                  <div className="text-purple-400 font-mono text-xl mb-2">TARGET PAPER</div>
                  <div className="text-white text-3xl font-bold mb-4 leading-snug">
                    "Deep Reinforcement Learning for Supply Chain and Price Management"
                  </div>
                  <div className="text-gray-500 font-mono text-sm">(arXiv:2204.09603)</div>
                </div>
              </RevealBox>
            </div>
            <div className="md:col-span-7 flex flex-col justify-center gap-6">
              <RevealBox delay={0.2}>
                <p className="mb-4">
                  We drew a direct parallel to this landmark 2023 paper. They constructed the original "SCIMAI-Gym" simulator to prove that RL agents could outperform traditional (s,Q) heuristics in a standard 1-Product, 1-Warehouse environment.
                </p>
                <p>
                  <strong>Our Project's Relationship:</strong> Unlike toy models, we took the rigorous path. We spent Phase 1 meticulously rebuilding their environment parameters from scratch and trained our agents to prove we could <strong>replicate their published numbers</strong>. We mathematically aligned our simulator to their gravity before extending it with novel LLM disruption logic.
                </p>
              </RevealBox>
            </div>
          </div>
        </SectionContainer>

        {/* --- 4. METHODOLOGY & ARCHITECTURE --- */}
        <SectionContainer>
          <SectionHeader title="3. Methodology & Architecture" subtitle="FROM BASELINE REPLICATION TO NOVEL CAPABILITY" />
          
          <div className="grid md:grid-cols-2 gap-8 mt-12">
            <div className="space-y-8">
              <RevealBox title="Phase 1: Environment & Baselines" color="text-purple-400" delay={0.1}>
                <ul className="space-y-4 text-gray-300 font-light">
                  <li>
                    <strong className="text-white">The Simulator:</strong> We built <code>ScimaiEnv</code>, a rigorous Gymnasium environment tracking warehouse inventory, shipments, backlogs, and daily demand.
                  </li>
                  <li>
                    <strong className="text-white">The Agents:</strong> Deployed powerful RL algorithms (Proximal Policy Optimization & A2C). Agents observed state and learned purely via trial and error over <strong>300,000 interactions</strong> to maximize profit.
                  </li>
                </ul>
              </RevealBox>
            </div>

            <div className="space-y-8">
              <RevealBox title="Phase 2: Disruption & LLM Oracle" color="text-cyan-400" delay={0.3} highlight>
                <ul className="space-y-4 text-gray-200 font-light">
                  <li>
                    <strong className="text-white">Disruption Generator:</strong> Injected chaos using regimes: <em>Frequent-Short</em> (constant minor delays), <em>Infrequent-Long</em> (rare massive delays), and <em>Stress Tests</em>.
                  </li>
                  <li>
                    <strong className="text-cyan-300">The LLM Oracle:</strong> Instead of expensive API calls, we built a rule-based "Oracle News Module". It simulates an LLM reading a headline (e.g. "SEVERE HURRICANE WARNING") and outputs a smooth probabilistic risk score (e.g., 0.87).
                  </li>
                </ul>
              </RevealBox>
            </div>
          </div>
        </SectionContainer>

        {/* --- 5. HOW EXACTLY DO OUR NUMBERS COMPARE? --- */}
        <SectionContainer>
          <SectionHeader title="4. Empirical Results" subtitle="HOW EXACTLY DO OUR NUMBERS COMPARE?" />
          
          <RevealBox delay={0.1} className="mb-12 border border-purple-500/30">
            <h3 className="text-2xl font-bold font-sans text-white mb-6">Phase 1: Replication Validation</h3>
            <div className="grid md:grid-cols-3 gap-6">
              <StatBlock label="Oracle Model" expected="1474" actual="1455" delta="1.3% Delta" success />
              <StatBlock label="A2C Algorithm" expected="870" actual="829" delta="4.7% Delta" success />
              <StatBlock label="PPO Algorithm" expected="1213" actual="1602" delta="32% Outperform" info reason="Modern SB3 normalisation outperforms Ray/RLlib 1.5.2" />
            </div>
          </RevealBox>

          <RevealBox delay={0.2} highlight glowColor="rgba(6,182,212,0.15)">
            <h3 className="text-3xl font-bold font-sans text-cyan-400 mb-8 flex items-center gap-4">
              <span className="w-3 h-3 rounded-full bg-cyan-400 animate-pulse"></span>
              Phase 2: Core Discovery
            </h3>
            <p className="text-gray-300 font-mono text-sm uppercase tracking-widest mb-8 border-b border-white/10 pb-4">
              The "Frequent-Short" Disruption Regime (100 Episodes)
            </p>
            
            <div className="grid md:grid-cols-3 gap-8 text-center mb-10">
              <div>
                <div className="text-gray-400 font-mono text-sm mb-2">PPO Blind</div>
                <div className="text-5xl font-bold text-white mb-2">1,031</div>
                <div className="text-sm text-gray-500">Baseline Profit</div>
              </div>
              <div className="relative">
                <div className="absolute -inset-4 bg-red-500/10 rounded-2xl blur-xl"></div>
                <div className="relative">
                  <div className="text-red-400 font-mono text-sm mb-2">Disrupt-Aware PPO</div>
                  <div className="text-5xl font-bold text-red-400 mb-2">398</div>
                  <div className="text-sm text-red-300/70">61% Profit Collapse</div>
                </div>
              </div>
              <div className="relative">
                <div className="absolute -inset-4 bg-green-500/10 rounded-2xl blur-xl"></div>
                <div className="relative">
                  <div className="text-green-400 font-mono text-sm mb-2">LLM-Augmented PPO</div>
                  <div className="text-5xl font-bold text-green-400 mb-2">984</div>
                  <div className="text-sm text-green-300/70">Avoids trap entirely</div>
                </div>
              </div>
            </div>

            <div className="bg-black/50 p-6 rounded-2xl border border-white/5 text-gray-200 font-light text-lg">
              <strong className="text-white">The Meaning:</strong> We mathematically proved <span className="text-cyan-400 font-mono text-sm bg-cyan-900/30 px-2 py-1 rounded">(t=5.43, p &lt; 0.0001)</span> that simply handing an AI a binary "Disaster = True/False" flag causes it to intensely over-react and destroy its own profits through extreme over-hedging. 
              However, feeding the AI our smooth, continuous LLM "risk score" allows it to learn nuanced restraint. The LLM semantic signal completely prevents the AI from falling into the over-hedging trap.
            </div>
          </RevealBox>
        </SectionContainer>

        {/* --- 6. FUTURE IMPROVEMENTS --- */}
        <SectionContainer>
          <SectionHeader title="5. Possible Future Improvements" subtitle="EXPANDING THE HORIZON" />
          <div className="grid md:grid-cols-3 gap-6">
            <RevealBox title="Live LLM Integration" delay={0.1}>
              <p className="text-gray-400 font-light">
                Wiring up a live, localized small-language model (like Llama-3 8B) during the evaluation phase to classify raw, unseen real-world Reuters or Bloomberg news streams in real-time.
              </p>
            </RevealBox>
            <RevealBox title="Multi-Echelon Networks" delay={0.2}>
              <p className="text-gray-400 font-light">
                Upgrading the Gym environment to a multi-node network (Factory → Distribution Center → Local Retailer) to test if the LLM-augmented agent can learn the "Bullwhip Effect" across complex supply lines.
              </p>
            </RevealBox>
            <RevealBox title="Variable Pricing" delay={0.3}>
              <p className="text-gray-400 font-light">
                Currently, good prices are fixed. Allowing the RL agent to dynamically surge or lower prices during a stockout/disruption (Yield Management) might discover entirely alien strategies for buffering supply constraints.
              </p>
            </RevealBox>
          </div>
        </SectionContainer>

        {/* --- FOOTER --- */}
        <footer className="w-full py-12 pb-24 text-center text-gray-600 font-mono text-xs md:text-sm border-t border-white/5 bg-black/80 backdrop-blur-md mt-32 flex flex-col items-center gap-2">
           <p className="text-gray-400">Made by Arav, Madhan and Shubhdeep</p>
           <p className="mt-4">Engineered for the Stranieri & Stella (2023) architecture replication and expansion.</p>
           <p className="text-gray-500">React + Three.js + Framer Motion + Stable-Baselines3</p>
        </footer>

      </div>
    </div>
  );
}

// --- Helper Components for Layout & Animation ---

function SectionContainer({ children, reverse }) {
  return (
    <section className="py-24 md:py-32 px-6 w-full max-w-6xl mx-auto">
      <div className={`w-full flex flex-col ${reverse ? 'items-end' : 'items-start'}`}>
        {children}
      </div>
    </section>
  );
}

function SectionHeader({ title, subtitle, textAlign = "left" }) {
  return (
    <motion.div 
      initial={{ opacity: 0, y: 30 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, margin: "-100px" }}
      className={`mb-12 w-full ${textAlign === "right" ? "text-right" : "text-left"}`}
    >
      <div className="font-mono text-cyan-400 text-sm tracking-widest mb-3 uppercase">{subtitle}</div>
      <h2 className="text-4xl md:text-6xl font-bold font-sans text-transparent bg-clip-text bg-gradient-to-r from-gray-100 to-gray-400 leading-tight pb-2">
        {title}
      </h2>
    </motion.div>
  );
}

function RevealBox({ title, color = "text-white", children, delay = 0, highlight, glowColor, className = "" }) {
  const baseClasses = highlight 
    ? "bg-white/10 border-white/20 shadow-2xl backdrop-blur-xl" 
    : "bg-white/5 border-white/10 backdrop-blur-lg";

  return (
    <motion.div
      initial={{ opacity: 0, y: 40 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, margin: "-100px" }}
      transition={{ duration: 0.8, delay, ease: "easeOut" }}
      className={`p-8 md:p-10 rounded-[2rem] border ${baseClasses} ${className}`}
      style={{ boxShadow: glowColor ? `0 0 50px ${glowColor}` : undefined }}
    >
      {title && <h3 className={`text-2xl font-bold font-sans mb-6 ${color}`}>{title}</h3>}
      {children}
    </motion.div>
  );
}

function StatBlock({ label, expected, actual, delta, success, info, reason }) {
  return (
    <div className="bg-black/40 p-6 rounded-2xl border border-white/5 flex flex-col">
      <div className="font-mono text-gray-400 text-sm mb-4">{label}</div>
      <div className="flex justify-between items-end mb-2">
        <div>
          <div className="text-xs text-gray-500 uppercase tracking-wider mb-1">Paper</div>
          <div className="text-xl text-gray-300 font-bold">{expected}</div>
        </div>
        <div className="text-right">
          <div className="text-xs text-cyan-500 uppercase tracking-wider mb-1">Ours</div>
          <div className="text-3xl text-white font-bold">{actual}</div>
        </div>
      </div>
      <div className={`mt-auto pt-4 border-t border-white/5 font-mono text-sm font-bold flex justify-between ${success ? 'text-green-400' : info ? 'text-blue-400' : 'text-amber-400'}`}>
        <span>{delta}</span>
        {success && <span>✓ MATCH</span>}
        {info && <span>↗ EXCEEDS</span>}
      </div>
      {reason && (
        <div className="mt-3 text-xs text-gray-500 font-sans leading-relaxed">
          {reason}
        </div>
      )}
    </div>
  );
}
